version: '2'
services:
  foreman:
    build:
      context: foreman
      args:
        foreman_version: 1.13-stable
        foreman_mode: production
    environment:
      FOREMAN_MODE: production
      BUNDLE_WITHOUT: "mysql:test:mysql2:development:sqlite:jenkins:openid:libvirt"
    command: rails server -p 80 -b 0.0.0.0
    ports:
      - 80
    volumes:
      - ./.assets-cache/production/assets:/usr/src/foreman/public/assets:z
      - ./.assets-cache/production/webpack:/usr/src/foreman/public/webpack:z
    links:
      - db
      - memcache
      - proxy

  memcache:
    image: memcached

  db:
    image: postgres:9.5
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata:z

  haproxy:
    image: dockercloud/haproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - foreman
    ports:
      - 80:80
      - 1936:1936
  proxy:
    build: proxy
    command: /usr/src/app/bin/smart-proxy
    ports:
      - 8000:8000
  client:
    build: client
    environment:
      - FOREMAN_URL=http://haproxy
    depends_on:
      - haproxy
