production: &default
  adapter: <%= ENV['DB_ADAPTER'] ||= 'postgresql' %>
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: db

development:
  <<: *default
  database: foreman_development

test:
  <<: *default
  database: foreman_test
